name: Automated Content Update

on:
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout OATutor repository
      uses: actions/checkout@v2
      with:
        ref: 'content-staging'  # Checkout the content-staging branch

    - name: Clone OATutor-Tooling repository
      run: git clone https://github.com/CAHLR/OATutor-Tooling.git /home/runner/work/OATutor-Tooling

    - name: Install distutils and build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-distutils build-essential meson ninja-build python3-dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Upgrade pip and install Python dependencies
      run: |
        pip install --upgrade pip
        pip install --prefer-binary -r /home/runner/work/OATutor-Tooling/content_script/requirements.txt

    - name: Create credentials JSON file
      run: echo "${{ secrets.OATUTOR_JSON_KEY }}" | base64 --decode > oatutor-askoski-f122840466c4.json

    - name: Set environment variable for spreadsheet key
      run: echo "URL_SPREADSHEET_KEY=${{ secrets.URL_SPREADSHEET_KEY }}" >> $GITHUB_ENV

    - name: Remove existing content
      run: rm -rf /home/runner/work/OATutor/OATutor/src/content-sources/oatutor/*

    - name: Create Content Directory
      run: mkdir -p /home/runner/work/OATutor/OATutor/src/content-sources/oatutor/Content

    - name: Run content update script
      run: |
        python3 /home/runner/work/OATutor-Tooling/content_script/final.py online full

    - name: Move and prepare files
      run: |
        cd /home/runner/work/OATutor/OATutor/src/content-sources/oatutor
        mv "OpenStax Content" "content-pool"
        mkdir -p bkt-params
        mv bktParams.json bkt-params/bktParams1.json
        cp bkt-params/bktParams1.json bkt-params/bktParams2.json

    - name: Run Node.js preprocessing script
      run: |
        cd /home/runner/work/OATutor/OATutor/src/tools
        node preprocessProblemPool.js

    - name: Configure Git
      run: |
        git config user.email "generic@example.com"
        git config user.name "Generic User"

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Automated content update"
        git push origin content-staging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
